services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: retail-erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senali2001
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: erp-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/retail-erp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senali2001
    depends_on:
      - db